# coding: utf-8

"""
    OSRM API v5.22.0

    Open Source Routing Machine API  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osrm_api
from osrm_api.api.default_api import DefaultApi  # noqa: E501
from osrm_api.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = osrm_api.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_route(self):
        """Test case for route

        """
        pass


if __name__ == '__main__':
    unittest.main()
