# coding: utf-8

"""
    OSRM API v5.22.0

    Open Source Routing Machine API  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "osrm-api"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="OSRM API v5.22.0",
    author_email="1love1papaya@gmail.com",
    url="https://github.com/1papaya/python-osrm-openapi",
    keywords=["OpenAPI", "OpenAPI-Generator", "OSRM API v5.22.0"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    Open Source Routing Machine API  # noqa: E501
    """
)
